# 字体大小
font_size 15.0
font_family      CaskaydiaMono Nerd Font
bold_font        CaskaydiaMono Nerd Font
italic_font      CaskaydiaMono Nerd Font
bold_italic_font CaskaydiaMono Nerd Font

globinclude kitty.d/**/*.conf

# 快捷键映射
map cmd+k send_text all claude -p ""

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME